version: '3.4'

services:
  nvbusiness:
    image: nvbusiness
    container_name: nvbusiness
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
